//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int IDPerson { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Cannot be more than 50 chars!")]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Cannot be more than 50 chars!")]
        public string LastName { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Cannot be more than 50 chars!")]
        public string Nationality { get; set; }
        [Required]
        public int Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
